version: "3.9"

services:
  real_estate_rag:
    build: .
    container_name: real_estate_rag
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
