name: CI - Real Estate RAG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Cache pip
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run smoke tests
      - name: Run smoke tests
        run: |
          python -m compileall .
          python -c "import app, embeddings, retriever, ingestion, utils"

      # Test Streamlit app launch
      - name: Test Streamlit app launch
        run: |
          streamlit run app.py --headless --server.headless true &
          sleep 10
          pkill -f streamlit || true
